BEGIN TRANSACTION;
INSERT INTO articles (id, title, slug, category, categories, date, end_date, author, status, cover_image, focus_keyword, meta_title, meta_description, canonical_url, content, seo_score, is_trashed) VALUES ('art-osn-matematika', 'Tips Belajar OSN Matematika SMA: Strategi Penguasaan 4 Pilar & Problem Solving Heuristik', 'tips-belajar-osn-matematika-sma', 'OSN & Sains', '["OSN \u0026 Sains","Tips Belajar \u0026 Prestasi"]', '2026-08-25', '', 'Kak Radit (Medalis OSN Matematika)', 'published', '/images/blog/cover-osn-matematika.jpg', 'tips belajar osn matematika sma', 'Tips Belajar OSN Matematika SMA: Strategi Juara 4 Pilar | NLS', 'Panduan lengkap tips belajar OSN Matematika SMA: bedah 4 pilar aljabar, geometri, teori bilangan, kombinatorika, dan metode problem solving medalis NLS.', 'https://next-level-study.com/blog/tips-belajar-osn-matematika-sma', '<h2>Mengapa OSN Matematika Membutuhkan Pola Pikir Pembuktian Logis?</h2>
<p>Olimpiade Sains Nasional (OSN) Matematika jenjang SMA bukanlah sekadar tes kecepatan berhitung, melainkan uji ketajaman logika berpikir deduktif dan seni pembuktian matematis yang elegan. Berbeda dengan soal ujian sekolah standar yang bersifat algoritmik, soal olimpiade dirancang non-rutin, menantang peserta untuk menemukan jalan keluar kreatif dari permasalahan abstrak.</p>

<h3>1. Menguasai 4 Pilar Utama Materi OSN Matematika</h3>
<p>Silabus resmi Balai Pengembangan Talenta Indonesia (BPTI) membagi materi olimpiade matematika ke dalam empat cabang fundamental yang saling beririsan:</p>
<ul>
  <li><strong>Aljabar:</strong> Polinomial lanjutan, sistem persamaan tak linear, teori fungsi, serta pertidaksamaan klasik seperti Cauchy-Schwarz, AM-GM, dan Jensen.</li>
  <li><strong>Geometri:</strong> Sifat lingkaran, kesebangunan & kongruensi segitiga, titik istimewa segitiga (Orthocenter, Incenter, Circumcenter), teorema Ceva, Menelaus, Ptolemy, hingga Power of a Point.</li>
  <li><strong>Teori Bilangan:</strong> Modulo aritmatika, keterbagian, teorema sisa Tiongkok (CRT), Teorema Kecil Fermat, Teorema Wilson, dan persamaan Diophantine.</li>
  <li><strong>Kombinatorika:</strong> Prinsip Sarang Burung (Pigeonhole Principle), Prinsip Inklusi-Eksklusi, Double Counting, Teori Graf dasar, dan relasi rekurensi.</li>
</ul>

<h3>2. Menerapkan Metode Heuristik Polya dalam Memecahkan Soal</h3>
<p>Ketika berhadapan dengan soal sulit berbobot kompetisi, jangan langsung terburu-buru menulis rumus. Terapkan empat langkah heuristik George Polya: (1) Pahami kondisi dan batasan masalah secara mendalam, (2) Rancang rencana pembuktian (misal: induksi matematika, kontradiksi, atau konstruksi aljabar), (3) Jalankan rencana dengan ketelitian logika tingkat tinggi, dan (4) Tinjau kembali (Look Back) untuk memverifikasi apakah ada celah dalam argumen Anda.</p>

<h3>3. Rekomendasi Buku Rujukan & Sumber Latihan Teruji</h3>
<p>Gunakan buku standar olimpiade internasional seperti <em>Problem-Solving Strategies</em> karya Arthur Engel, <em>Euclidean Geometry in Mathematical Olympiads (EGMO)</em> karya Evan Chen, dan modul pembinaan resmi pelatnas NLS. Analisis juga arsip soal OSN-K, OSN-P, OSN Nasional, hingga soal seleksi IMO (International Mathematical Olympiad).</p>

<h3>4. Manajemen Jadwal Belajar dan Siklus Evaluasi Mandiri</h3>
<p>Disiplin adalah pembeda utama antara peserta biasa dan peraih medali. Alokasikan waktu minimal 2-3 jam setiap hari secara konsisten. Fokuslah pada kedalaman pemahaman daripada kuantitas soal semata. Mengerjakan 3 soal pembuktian yang rumit dan merefleksikan solusinya jauh lebih efektif dibanding menjawab 30 soal pilihan ganda sederhana.</p>

<h3>5. Membangun Daya Tahan Mental dan Resiliensi Kompetisi</h3>
<p>Waktu pengerjaan OSN tingkat provinsi dan nasional sangat panjang (biasanya 4 jam untuk 4-5 soal uraian). Daya tahan konsentrasi, ketenangan saat menemukan jalan buntu, dan manajemen waktu per soal harus dilatih melalui simulasi ujian berkala di platform CBT Next Level Study.</p>

<blockquote>"Dalam olimpiade matematika, keindahan solusi tidak terletak pada seberapa cepat Anda menemukan jawaban, melainkan seberapa kokoh dan elegan logika yang menopang argumen Anda."</blockquote>', 96, 0);
INSERT INTO articles (id, title, slug, category, categories, date, end_date, author, status, cover_image, focus_keyword, meta_title, meta_description, canonical_url, content, seo_score, is_trashed) VALUES ('art-osn-fisika', 'Tips Belajar OSN Fisika SMA: Metode Pemodelan Matematis, Analisis Kalkulus & Bedah Soal IPhO', 'tips-belajar-osn-fisika-sma', 'OSN & Sains', '["OSN \u0026 Sains","Tips Belajar \u0026 Prestasi"]', '2026-08-24', '', 'Kak Alvin (Medalis OSN Fisika)', 'published', '/images/blog/cover-osn-fisika.jpg', 'tips belajar osn fisika sma', 'Tips Belajar OSN Fisika SMA: Pemodelan & Kalkulus Medalis | NLS', 'Pelajari tips belajar OSN Fisika SMA dari pemodelan diagram benda bebas, kalkulus diferensial-integral, termodinamika hingga strategi bedah soal IPhO.', 'https://next-level-study.com/blog/tips-belajar-osn-fisika-sma', '<h2>Transformasi Pemahaman Fisika: Dari Hafalan Rumus Menuju Hukum Fundamental</h2>
<p>Banyak siswa menganggap fisika sebagai kumpulan rumus rumit yang harus dihafal. Namun, dalam ajang bergengsi OSN Fisika SMA, pendekatan hafalan dipastikan gagal total. Fisika olimpiade menuntut kemampuan menerjemahkan fenomena fisis nyata ke dalam bahasa matematika melalui pemodelan hukum-hukum alam fundamental.</p>

<h3>1. Integrasi Kalkulus Diferensial dan Integral Tingkat Lanjut</h3>
<p>Kalkulus adalah bahasa alami fisika. Peserta OSN Fisika wajib fasih menggunakan turunan parsial, integral lipat, persamaan diferensial sederhana, dan ekspansi deret Taylor. Konsep seperti kecepatan sebagai turunan posisi, gaya sebagai gradien potensial, dan hukum Gauss dalam medan listrik tidak dapat dipahami utuh tanpa kalkulus.</p>

<h3>2. Kuasai Domain Materi Utama Silabus OSN Fisika</h3>
<ul>
  <li><strong>Mekanika Klasik:</strong> Kinematika analitik, dinamika rotasi benda tegar, momen inersia variabel, osilasi harmonik teredam, pusat massa, dan hukum gravitasi orbit elips Kepler.</li>
  <li><strong>Elektrodinamika & Magnetisme:</strong> Hukum Coulomb, Hukum Gauss, potensial elektrostatik, rangkaian RLC transien, hukum Biot-Savart, gaya Lorentz, dan induksi Faraday-Lenz.</li>
  <li><strong>Termodinamika & Fisika Statistik:</strong> Teori kinetik gas ideal, hukum I & II termodinamika, siklus mesin kalor Carnot & Otto, perubahan entropi, dan kapasitas kalor molar.</li>
  <li><strong>Gelombang, Optik & Fisika Modern:</strong> Interferensi celah ganda, difraksi kisi, polarisasi, efek Doppler relativistik, dualisme gelombang-partikel, dan model atom kuantum Bohr.</li>
</ul>

<h3>3. Teknik Visualisasi Melalui Free Body Diagram (FBD) Presisi</h3>
<p>Kunci keberhasilan memecahkan soal mekanika adalah keakuratan membuat Free Body Diagram (FBD). Gambarkan semua vektor gaya yang bekerja pada tiap komponen sistem secara terpisah, pilih sistem koordinat kartesius atau polar yang menyederhanakan perhitungan, lalu terapkan hukum II Newton atau prinsip kekekalan energi mekanik.</p>

<h3>4. Buku Panduan Wajib Rekomendasi Mentor Medalis</h3>
<p>Mulailah dari literatur standar universitas seperti <em>Physics for Scientists and Engineers</em> oleh Serway-Jewett atau Halliday-Resnick. Untuk latihan soal tantangan tingkat tinggi, pelajari buku legendaris <em>200 Puzzling Physics Problems</em> (Gnadig) dan bank soal IPhO/APhO terbitan TOFI.</p>

<h3>5. Memaksimalkan Nilai pada Ujian Praktikum Eksperimen</h3>
<p>Pada tingkat nasional, 30-40% total nilai berasal dari tes praktikum. Latihlah keterampilan merangkai alat laboratorium, membaca jangka sorong & mikroskop, mengoperasikan osiloskop digital, serta menyusun tabel data dengan analisis regresi linier dan perambatan ketidakpastian (uncertainty analysis).</p>

<blockquote>"Fisika bukanlah sekadar angka dan persamaan, melainkan seni melihat pola harmoni alam semesta melalui kacamata matematika presisi."</blockquote>', 95, 0);
INSERT INTO articles (id, title, slug, category, categories, date, end_date, author, status, cover_image, focus_keyword, meta_title, meta_description, canonical_url, content, seo_score, is_trashed) VALUES ('art-osn-kimia', 'Tips Belajar OSN Kimia SMA: Kuasai Mekanisme Reaksi Organik, Termodinamika & Spektroskopi', 'tips-belajar-osn-kimia-sma', 'OSN & Sains', '["OSN \u0026 Sains","Tips Belajar \u0026 Prestasi"]', '2026-08-23', '', 'Kak Nadia (Tutor Spesialis OSN Kimia)', 'published', '/images/blog/cover-osn-kimia.jpg', 'tips belajar osn kimia sma', 'Tips Belajar OSN Kimia SMA: Reaksi Organik & Termodinamika | NLS', 'Panduan tips belajar OSN Kimia SMA: strategi mendalam kimia fisik, reaksi organik, stoikiometri analitik, dan analisis spektroskopi NMR bersama NLS.', 'https://next-level-study.com/blog/tips-belajar-osn-kimia-sma', '<h2>Kunci Menguasai Kimia Kompetisi: Keseimbangan Antara Teori dan Logika Reaksi</h2>
<p>Olimpiade Sains Nasional Kimia SMA terkenal dengan cakupan materinya yang sangat luas, menjangkau level perkuliahan kimia tingkat dua dan tiga. Untuk meraih medali juara, siswa harus mampu menggabungkan kalkulasi kuantitatif yang presisi pada kimia fisik dengan penalaran kualitatif pada mekanisme reaksi organik dan struktur anorganik.</p>

<h3>1. Fondasi Kimia Fisik: Termodinamika & Kinetika Reaksi</h3>
<p>Kimia fisik menjadi tulang punggung dari 40% soal olimpiade. Pelajari secara mendalam konsep Entalpi (Delta H), Entropi (Delta S), dan Energi Bebas Gibbs (Delta G). Pahami hubungan kesetimbangan kimia dengan konstanta Van ''t Hoff, elektrokimia persamaan Nernst, serta hukum laju reaksi terintegrasi orde 0, 1, dan 2.</p>

<h3>2. Memahami Logika Mekanisme Reaksi Kimia Organik</h3>
<p>Alih-alih menghafal ratusan reaksi organik, pahamilah perpindahan elektron melalui notasi panah lengkung (curved arrow mechanism). Kuasai konsep nukleofil-elektrofil, efek induksi, resonansi, sterik, serta mekanisme reaksi penting seperti substitusi nukleofilik (SN1, SN2), eliminasi (E1, E2), adisi elektrofilik alkena, hingga reaksi kondensasi karbonil (Aldol, Claisen).</p>

<h3>3. Analisis Spektroskopi Molekuler Modern</h3>
<p>Soal OSN tingkat provinsi dan nasional rutin menghadirkan soal penentuan struktur molekul tak dikenal melalui kombinasi data spektrum: 1H-NMR, 13C-NMR, Spektroskopi Inframerah (FT-IR), Spektrometri Massa (MS), dan Spektroskopi UV-Vis. Latihlah kepekaan membaca chemical shift, splitting pattern, dan indeks defisiensi hidrogen (IDH).</p>

<h3>4. Kimia Anorganik & Kompleks Logam Transisi</h3>
<p>Kuasai konfigurasi elektron ion transisi, geometri molekul VSEPR, teori ikatan valensi, serta Teori Medan Kristal (Crystal Field Theory). Pahami pembagian orbital d, faktor penentu high-spin/low-spin, efek Jahn-Teller, dan deret spektrokimia ligan.</p>

<h3>5. Referensi Belajar Standar Internasional</h3>
<p>Buku rujukan utama yang wajib dipelajari meliputi <em>Chemistry</em> karya Zumdahl atau Raymond Chang untuk kimia umum, <em>Physical Chemistry</em> karya Peter Atkins, dan <em>Organic Chemistry</em> karya Paula Yurkanis Bruice atau Jonathan Clayden. Bedah soal-soal IChO (International Chemistry Olympiad) untuk melatih daya nalar tingkat tinggi.</p>

<blockquote>"Di balik setiap tabung reaksi dan perubahan warna larutan, tersimpan hukum-hukum termodinamika dan pergerakan elektron yang menanti untuk dipecahkan secara matematis."</blockquote>', 94, 0);
INSERT INTO articles (id, title, slug, category, categories, date, end_date, author, status, cover_image, focus_keyword, meta_title, meta_description, canonical_url, content, seo_score, is_trashed) VALUES ('art-osn-biologi', 'Tips Belajar OSN Biologi SMA: Pemahaman Konseptual Terpadu Campbell & Analisis Data Eksperimen IBO', 'tips-belajar-osn-biologi-sma', 'OSN & Sains', '["OSN \u0026 Sains","Tips Belajar \u0026 Prestasi"]', '2026-08-22', '', 'Kak Zahra (Medalis OSN Biologi)', 'published', '/images/blog/cover-osn-biologi.jpg', 'tips belajar osn biologi sma', 'Tips Belajar OSN Biologi SMA: Analisis Konsep & Data IBO | NLS', 'Tips belajar OSN Biologi SMA terstruktur: kuasai biologi sel, genetika molekuler, fisiologi komparatif, dan analisis data eksperimen sains IBO.', 'https://next-level-study.com/blog/tips-belajar-osn-biologi-sma', '<h2>Membongkar Mitos: OSN Biologi Bukan Sekadar Hafalan Istilah Latin</h2>
<p>Banyak calon peserta olimpiade gugur di tahap awal karena mengira belajar biologi hanya sebatas menghafal nama ilmiah dan deskripsi morfologi. Pada kenyataannya, OSN Biologi jenjang SMA berfokus penuh pada pemikiran analitis berbasis data eksperimental, pemahaman mekanisme molekuler kaskade seluler, dan deduksi logis diagram genetik.</p>

<h3>1. Menuntaskan ''Kitab Suci'' Campbell Biology</h3>
<p>Buku <em>Campbell Biology</em> (edisi 11 atau 12) adalah fondasi mutlak yang harus dikuasai bab per bab. Jangan hanya membaca teks, perhatikan secara cermat setiap diagram jalur sinyal sel, skema siklus biokimia, grafik respon fisiologis, serta penjelasan eksperimen ilmiah yang ada di setiap akhir subbab.</p>

<h3>2. Pemetaan 7 Cabang Materi Silabus OSN Biologi</h3>
<ul>
  <li><strong>Biologi Sel & Molekuler (20%):</strong> Struktur membran, transport vesikel, respirasi seluler, fotosintesis C3/C4/CAM, replikasi DNA, ekspresi gen operon, CRISPR, dan PCR.</li>
  <li><strong>Anatomi & Fisiologi Tumbuhan (15%):</strong> Jaringan xilem-floem, mekanisme stomata, fitohormon (auksin, giberelin, asam absisat), dan fotoperiodisme.</li>
  <li><strong>Anatomi & Fisiologi Hewan/Manusia (25%):</strong> Sistem saraf & potensial aksi, endokrinologi, sistem sirkulasi, ekskresi nefron ginjal, serta imunologi sel T dan antibodi.</li>
  <li><strong>Genetika & Evolusi (20%):</strong> Persilangan Mendel, linkage & rekombinasi, peta genetik kuantitatif, genetika populasi Hardy-Weinberg, dan kladogram filogeni.</li>
  <li><strong>Ekologi & Etologi (15%):</strong> Aliran energi trofik, siklus biogeokimia, dinamika populasi r/K-seleksi, dan perilaku hewan bawaan versus belajar.</li>
  <li><strong>Biosistematika (5%):</strong> Taksonomi kladistik domain Archaea, Bakteri, Protista, Fungi, Plantae, dan Animalia.</li>
</ul>

<h3>3. Strategi Analisis Soal True/False Format IBO</h3>
<p>Format soal OSN Biologi terkini mengadopsi standar International Biology Olympiad (IBO), di mana 1 narasi eksperimen disertai grafik kompleks memuat 4 pernyataan (A, B, C, D) yang harus dinilai Benar atau Salah secara independen. Latihlah kebiasaan membaca label sumbu grafik, memahami kontrol positif/negatif, dan menghindari asumsi di luar data yang disajikan.</p>

<h3>4. Penguasaan Keterampilan Praktikum Laboratorium</h3>
<p>Bagi peserta yang lolos ke tingkat nasional, tes praktikum mencakup 4 laboratorium: Biologi Sel Molekuler (elektroforesis gel), Anatomi Fisiologi Tumbuhan (sayatan preparat melintang), Anatomi Hewan (diseksi invertebrata/vertebrata), serta Biosistematika & Ekologi.</p>

<blockquote>"Biologi adalah studi tentang keajaiban kehidupan yang bekerja secara presisi di level molekuler hingga keseimbangan biosfer global."</blockquote>', 95, 0);
INSERT INTO articles (id, title, slug, category, categories, date, end_date, author, status, cover_image, focus_keyword, meta_title, meta_description, canonical_url, content, seo_score, is_trashed) VALUES ('art-osn-informatika', 'Tips Belajar OSN Informatika SMA: Competitive Programming C++, Optimasi Algoritma & Dynamic Programming', 'tips-belajar-osn-informatika-sma', 'OSN & Sains', '["OSN \u0026 Sains","Tips Belajar \u0026 Prestasi"]', '2026-08-21', '', 'Kak Kevin (Medalis OSN Informatika)', 'published', '/images/blog/cover-osn-informatika.jpg', 'tips belajar osn informatika sma', 'Tips Belajar OSN Informatika SMA: Algoritma C++ & DP | NLS', 'Kupas tuntas tips belajar OSN Informatika SMA: competitive programming C++, struktur data lanjut, graph theory, dan optimasi waktu O(N log N).', 'https://next-level-study.com/blog/tips-belajar-osn-informatika-sma', '<h2>Mengapa OSN Informatika Adalah Ajang Competitive Programming Terbaik?</h2>
<p>OSN Informatika (Komputer) merupakan salah satu bidang paling dinamis dan menantang di era digital. Kompetisi ini menguji kemampuan logika komputasi murni, perancangan algoritma efisien, dan penerjemahan ide pemecahan masalah ke dalam kode program C++ yang mampu mengeksekusi jutaan data dalam batas waktu kurang dari satu detik (Time Limit 1.0s).</p>

<h3>1. Kuasai Bahasa Pemrograman C++ dan STL (Standard Template Library)</h3>
<p>Bahasa C++ adalah standar mutlak dalam ajang OSN dan International Olympiad in Informatics (IOI). Kuasai penggunaan struktur data bawaan STL seperti vector, set, map, priority_queue, dan algoritma bawaan seperti sort, lower_bound, serta manipulasi bitwise.</p>

<h3>2. Pemahaman Analisis Kompleksitas Waktu dan Memori (Big-O Notation)</h3>
<p>Sebelum menulis sebaris kode pun, hitunglah batasan input N. Jika N <= 10^5, algoritma O(N^2) dipastikan akan mendapatkan Time Limit Exceeded (TLE). Anda wajib merancang solusi efisien berorde O(N log N) atau O(N) menggunakan teknik struktur data lanjutan.</p>

<h3>3. Kuasai Paradigma Algoritma Fundamental</h3>
<ul>
  <li><strong>Brute Force & Complete Search:</strong> Rekursi, backtracking, dan pemangkasan cabang (pruning).</li>
  <li><strong>Greedy Algorithms:</strong> Pemilihan langkah optimal lokal yang menghasilkan optimal global (contoh: Activity Selection, Fractional Knapsack).</li>
  <li><strong>Divide and Conquer:</strong> Binary Search on Answer, Merge Sort, dan Exponentiation by Squaring.</li>
  <li><strong>Dynamic Programming (DP):</strong> Knapsack 0/1, Longest Increasing Subsequence (LIS), DP on Trees, DP Bitmask, dan Digit DP.</li>
  <li><strong>Graph Theory:</strong> Breadth-First Search (BFS), Depth-First Search (DFS), Dijkstra''s Shortest Path, Minimum Spanning Tree (Kruskal/Prim), dan Disjoint Set Union (DSU).</li>
</ul>

<h3>4. Roadmap Latihan Rutin di Platform Online Judge</h3>
<p>Bergabunglah dan selesaikan tantangan secara rutin di platform <em>TLX Toki (TOKI Learning Center)</em>, <em>Codeforces</em>, <em>AtCoder</em>, dan <em>CSES Problem Set</em>. Mulailah dari menyelesaikan seluruh bab kursus pemrograman dasar dan kompetitif TLX sebelum mengikuti kontes rutin divisi 2 atau 3 di Codeforces.</p>

<h3>5. Manajemen Waktu 5 Jam Kontes Pemrograman</h3>
<p>Ujian OSN Informatika tingkat nasional berlangsung selama 5 jam untuk 3-4 soal bernilai 100 poin tiap soal. Terapkan strategi subtask hunting: amankan poin-poin subtask mudah terlebih dahulu sebelum menghabiskan waktu merancang algoritma full-score.</p>

<blockquote>"Kode program yang hebat bukan diukur dari panjang barisnya, melainkan dari keindahan struktur data dan keanggunan efisiensi kompleksitas algoritmanya."</blockquote>', 95, 0);
INSERT INTO articles (id, title, slug, category, categories, date, end_date, author, status, cover_image, focus_keyword, meta_title, meta_description, canonical_url, content, seo_score, is_trashed) VALUES ('art-osn-astronomi', 'Tips Belajar OSN Astronomi SMA: Visualisasi Trigonometri Bola Langit, Astrofisika & Mekanika Benda Langit', 'tips-belajar-osn-astronomi-sma', 'OSN & Sains', '["OSN \u0026 Sains","Tips Belajar \u0026 Prestasi"]', '2026-08-20', '', 'Kak Dimas (Medalis OSN Astronomi)', 'published', '/images/blog/cover-osn-astronomi.jpg', 'tips belajar osn astronomi sma', 'Tips Belajar OSN Astronomi SMA: Bola Langit & Astrofisika | NLS', 'Panduan lengkap tips belajar OSN Astronomi SMA: kuasai tata koordinat bola langit, hukum Kepler, fotometri bintang, dan pengolahan data teleskop.', 'https://next-level-study.com/blog/tips-belajar-osn-astronomi-sma', '<h2>Mengapa Astronomi Menjadi Kombinasi Sempurna Fisika dan Matematika Ruang Angkasa?</h2>
<p>Olimpiade Sains Nasional Astronomi SMA adalah salah satu cabang ilmu paling memikat. Di bidang ini, siswa ditantang menelaah misteri alam semesta melalui perpaduan harmonis antara mekanika fisika klasik, termodinamika radiasi, geometri bola langit 3 dimensi, dan analisis data pengamatan teleskop.</p>

<h3>1. Menguasai Sistem Tata Koordinat Bola Langit</h3>
<p>Fondasi terpenting astronomi posisi adalah visualisasi tata koordinat bola langit. Kuasai tiga sistem koordinat utama:</p>
<ul>
  <li><strong>Sistem Koordinat Horizon:</strong> Azimuth (A) dan Ketinggian (h) yang bergantung pada posisi geografis pengamat dan waktu lokal.</li>
  <li><strong>Sistem Koordinat Ekuatorial:</strong> Asensio Rekta (alpha) dan Deklinasi (delta) yang terikat pada ekuator langit dan titik Aries.</li>
  <li><strong>Sistem Koordinat Ekliptika:</strong> Garis edar tahunan Matahari dan bidang orbit planet-planet tata surya.</li>
</ul>

<h3>2. Aplikasi Trigonometri Bola (Spherical Trigonometry)</h3>
<p>Perhitungan segitiga bola navigasi astronomi membutuhkan rumus sinus dan cosinus bola: cos a = cos b cos c + sin b sin c cos A. Kuasai transformasi koordinat untuk menghitung waktu terbit/terbenam benda langit, sudut jam (HA), serta posisi Matahari pada waktu solstis dan ekuinoks.</p>

<h3>3. Mekanika Benda Langit & Astrofisika Bintang</h3>
<p>Pelajari secara komprehensif hukum-hukum gravitasi Newton, hukum I, II, III Kepler untuk orbit elips, kecepatan lepas, serta energi potensial gravitasi orbit. Pada cabang astrofisika, kuasai hukum radiasi benda hitam Planck, hukum pergeseran Wien, hukum Stefan-Boltzmann, magnitudo semu/mutlak, fotometri bintang, dan interpretasi Diagram Hertzsprung-Russell (HR-Diagram).</p>

<h3>4. Rekomendasi Buku Rujukan Utama</h3>
<p>Pelajari buku teks universitas seperti <em>Fundamental Astronomy</em> (Karttunen et al.), <em>An Introduction to Modern Astrophysics</em> (Carroll & Ostlie), serta modul pelatihan resmi pembinaan tim olimpiade astronomi Indonesia terbitan NLS.</p>

<h3>5. Keterampilan Analisis Data Pengamatan & Ronde Praktikum</h3>
<p>Pada tingkat nasional dan internasional (IOAA), peserta menghadapi ronde pengamatan malam menggunakan teleskop reflektor/refraktor, identifikasi rasi bintang pada peta langit (planetarium), serta ronde analisis data pengamatan menggunakan software astronomi.</p>

<blockquote>"Menatap langit malam bukan hanya tentang menikmati keindahan bintang, tetapi tentang memahami persamaan matematika yang mengatur orbit dan evolusi miliaran galaksi di alam semesta."</blockquote>', 94, 0);
INSERT INTO articles (id, title, slug, category, categories, date, end_date, author, status, cover_image, focus_keyword, meta_title, meta_description, canonical_url, content, seo_score, is_trashed) VALUES ('art-osn-kebumian', 'Tips Belajar OSN Kebumian SMA: Integrasi Geologi, Meteorologi, Oseanografi & Sistem Bumi Global', 'tips-belajar-osn-kebumian-sma', 'OSN & Sains', '["OSN \u0026 Sains","Tips Belajar \u0026 Prestasi"]', '2026-08-19', '', 'Kak Fajar (Medalis OSN Kebumian)', 'published', '/images/blog/cover-osn-kebumian.jpg', 'tips belajar osn kebumian sma', 'Tips Belajar OSN Kebumian SMA: Geologi & Sistem Atmosfer | NLS', 'Pelajari tips belajar OSN Kebumian SMA: identifikasi mineral batuan, dinamika atmosfer cuaca, oseanografi fisik, dan persiapan praktikum lapangan.', 'https://next-level-study.com/blog/tips-belajar-osn-kebumian-sma', '<h2>Memahami Bumi Sebagai Satu Kesatuan Sistem Dinamis Terpadu</h2>
<p>Ilmu Kebumian (Earth Science) adalah studi holistik yang meneliti interaksi kompleks antara Geosfer (litosfer & mantel), Atmosfer, Hidrosfer, dan pengaruh Astronomi Tata Surya terhadap dinamika planet Bumi. Dalam OSN Kebumian SMA, peserta diuji kemampuannya mengintegrasikan hukum fisika dan kimia untuk menjelaskan fenomena alam global.</p>

<h3>1. Geologi: Petrologi, Mineralogi, dan Tektonik Lempeng</h3>
<p>Kuasai pembentukan batuan beku, sedimen, dan metamorf melalui siklus batuan. Pelajari identifikasi sifat fisik mineral (kekerasan skala Mohs, kilap, gores, belahan), struktur geologi (sesar, lipatan, ketidakselarasan), stratigrafi hukum Steno, serta mekanisme pergerakan lempeng konvergen, divergen, dan transform.</p>

<h3>2. Meteorologi: Dinamika Cuaca dan Sirkulasi Atmosfer</h3>
<p>Pahami struktur lapisan atmosfer, radiasi matahari, kelembapan udara (spesifik & relatif), proses pembentukan awan, gaya Coriolis, angin geostrofik, serta fenomena iklim global seperti El Nino, La Nina, Dipole Mode, dan sirkulasi monsun di kepulauan Indonesia.</p>

<h3>3. Oseanografi: Fisika dan Kimia Samudra</h3>
<p>Pelajari profil suhu, salinitas, dan densitas kolom air laut (termoklin, haloklin, piknoklin). Kuasai mekanisme arus laut permukaan akibat angin (Spiral Ekman), sirkulasi termohalin laut dalam (Great Ocean Conveyor Belt), gelombang laut, dan dinamika pasang surut gravitasi Bulan-Matahari.</p>

<h3>4. Astronomi Planetologi & Geofisika</h3>
<p>Pahami struktur internal Bumi melalui rambatan gelombang seismik P dan S, medan magnet geomagnetik, proses diferensiasi planet kebumian (Terrestrial Planets), asteroid, komet, serta dampak tumbukan meteorik terhadap kepunahan massal dalam skala waktu geologi.</p>

<h3>5. Persiapan Ujian Praktikum Identifikasi Lapangan</h3>
<p>Di tahap nasional (dan seleksi IESO), peserta akan menghadapi tes praktikum identifikasi 20+ sampel mineral dan batuan asli, interpretasi peta topografi kontur & peta geologi regional, analisis peta sinoptik cuaca, serta pengukuran lapangan menggunakan kompas geologi Brunton.</p>

<blockquote>"Membaca lapisan batuan dan dinamika samudra adalah cara terbaik mendengarkan kisah sejarah perjalanan planet Bumi selama 4,5 miliar tahun terakhir."</blockquote>', 93, 0);
INSERT INTO articles (id, title, slug, category, categories, date, end_date, author, status, cover_image, focus_keyword, meta_title, meta_description, canonical_url, content, seo_score, is_trashed) VALUES ('art-osn-ekonomi', 'Tips Belajar OSN Ekonomi SMA: Logika Mikro-Makroekonomi, Jurnal Akuntansi & Analisis Isu Fiskal Global', 'tips-belajar-osn-ekonomi-sma', 'OSN & Sains', '["OSN \u0026 Sains","Tips Belajar \u0026 Prestasi"]', '2026-08-18', '', 'Kak Bima (Statistika & Ekonomi UGM)', 'published', '/images/blog/cover-osn-ekonomi.jpg', 'tips belajar osn ekonomi sma', 'Tips Belajar OSN Ekonomi SMA: Mikro-Makro & Akuntansi | NLS', 'Tips belajar OSN Ekonomi SMA terlengkap: bedah elastisitas pasar, pergeseran kurva makro, siklus jurnal akuntansi, dan studi kasus moneter IEO.', 'https://next-level-study.com/blog/tips-belajar-osn-ekonomi-sma', '<h2>Membangun Ketajaman Analisis Ekonomi: Dari Teori Pasar Hingga Kebijakan Publik</h2>
<p>Olimpiade Sains Nasional Bidang Ekonomi jenjang SMA menguji kematangan berpikir kritis dalam memecahkan masalah kelangkaan sumber daya, efisiensi alokasi pasar, stabilitas makroekonomi nasional, serta keterampilan teknis akuntansi keuangan perusahaan.</p>

<h3>1. Mikroekonomi: Teori Perilaku Konsumen, Produsen, dan Struktur Pasar</h3>
<p>Pahami fondasi kurva permintaan-penawaran, elastisitas harga/pendapatan/silang, surplus konsumen dan produsen, teori utilitas kardinal & ordinal (kurva indiferen dan budget line), fungsi produksi hukum kenaikan hasil yang makin berkurang (law of diminishing returns), serta perbandingan struktur pasar persaingan sempurna, monopoli, oligopoli, dan monopolistik.</p>

<h3>2. Makroekonomi: Pertumbuhan, Kebijakan Moneter dan Fiskal</h3>
<p>Kuasai perhitungan Pendapatan Nasional (PDB, PNB, NNI, Pendapatan Disposabel), teori inflasi dan indeks harga konsumen (IHK), pengangguran, fungsi konsumsi Keynes, kurva IS-LM, kebijakan moneter bank sentral (operasi pasar terbuka, suku bunga diskonto, rasio cadangan wajib), serta kebijakan anggaran fiskal pemerintah.</p>

<h3>3. Keterampilan Akuntansi Keuangan (Financial Accounting Mastery)</h3>
<p>Akuntansi menyumbang porsi nilai signifikan dalam OSN Ekonomi. Kuasai siklus akuntansi lengkap perusahaan jasa dan dagang: analisis transaksi debit-kredit, jurnal umum & khusus, buku besar, neraca saldo, jurnal penyesuaian (adjusting entries) untuk beban dibayar di muka & pendapatan diterima di muka, kertas kerja (worksheet), laporan laba rugi, laporan perubahan ekuitas, neraca, dan jurnal penutup.</p>

<h3>4. Ekonomi Internasional & Finansial Global</h3>
<p>Pelajari teori keunggulan mutlak Adam Smith & keunggulan komparatif David Ricardo, perdagangan internasional, tarif & kuota impor, pasar valuta asing (kurs mengambang bebas versus tetap), serta struktur Neraca Pembayaran Internasional (Current Account, Capital Account, Financial Account).</p>

<h3>5. Bedah Studi Kasus & Persiapan Kompetisi Internasional (IEO)</h3>
<p>Tingkat nasional dan International Economics Olympiad (IEO) menguji kemampuan <em>Financial Literacy Simulation</em> dan <em>Business Case Presentation</em>. Latihlah kemampuan membaca data statistik ekonomi terkini, menyusun esai analisis kebijakan moneter, dan mempresentasikannya secara percaya diri dalam bahasa Inggris.</p>

<blockquote>"Ekonomi bukan sekadar ilmu mencari keuntungan moneter, melainkan seni mengambil keputusan rasional terbaik demi kesejahteraan masyarakat secara berkelanjutan."</blockquote>', 94, 0);
INSERT INTO articles (id, title, slug, category, categories, date, end_date, author, status, cover_image, focus_keyword, meta_title, meta_description, canonical_url, content, seo_score, is_trashed) VALUES ('art-osn-geografi', 'Tips Belajar OSN Geografi SMA: Analisis Spasial Keruangan, SIG, Geomorfologi & Studi Lapangan Mandiri', 'tips-belajar-osn-geografi-sma', 'OSN & Sains', '["OSN \u0026 Sains","Tips Belajar \u0026 Prestasi"]', '2026-08-17', '', 'Kak Rian (Medalis OSN Geografi)', 'published', '/images/blog/cover-osn-geografi.jpg', 'tips belajar osn geografi sma', 'Tips Belajar OSN Geografi SMA: Analisis Spasial & SIG | NLS', 'Panduan tips belajar OSN Geografi SMA: interpretasi citra satelit, analisis SIG keruangan, geomorfologi wilayah, dan teknik esai argumentatif iGeo.', 'https://next-level-study.com/blog/tips-belajar-osn-geografi-sma', '<h2>Geografi Modern: Sintesis Sains Fisik, Sosial Keruangan, dan Teknologi Geospasial</h2>
<p>OSN Geografi SMA merupakan kompetisi multidisipliner yang menuntut pemahaman mendalam mengenai bentang alam bumi, interaksi manusia dengan lingkungan, tata ruang wilayah perkotaan, serta pemanfaatan teknologi mutakhir Sistem Informasi Geografis (SIG) dan Penginderaan Jauh.</p>

<h3>1. Geografi Fisik: Geomorfologi, Hidrologi, dan Biogeografi</h3>
<p>Pahami proses endogen (tektonisme, vulkanisme, seisme) dan proses eksogen (pelapukan, erosi, sedimentasi, mass wasting) yang membentuk bentang alam karst, glasial, aeolian, dan fluvial. Kuasai siklus hidrologi DAS (Daerah Aliran Sungai), debit air permukaan, serta sebaran bioma flora-fauna dunia berdasarkan garis Wallace-Weber.</p>

<h3>2. Geografi Manusia, Urbanisasi, dan Tata Ruang Kota</h3>
<p>Pelajari dinamika kependudukan (natalitas, mortalitas, migrasi, bonus demografi), model struktur ruang kota (Konsentris Burgess, Sektoral Hoyt, Inti Berganda Harris-Ullman), interaksi desa-kota model gravitasi Reilly, serta tantangan pembangunan berkelanjutan (SDGs).</p>

<h3>3. Penginderaan Jauh & Sistem Informasi Geografis (SIG)</h3>
<p>Kuasai prinsip interpretasi citra satelit dan foto udara melalui 8 unsur interpretasi (rona, warna, bentuk, ukuran, tekstur, pola, bayangan, situs, asosiasi). Pahami komponen data spasial vektor-raster, analisis tumpang-susun peta (overlay buffer), dan sistem proyeksi peta (Mercator, UTM).</p>

<h3>4. Mitigasi Kebencanaan dan Manajemen Lingkungan Hidup</h3>
<p>Sebagai negara di kawasan Cincin Api Pasifik (Ring of Fire), peserta OSN Geografi Indonesia wajib memahami siklus manajemen bencana: pra-bencana (mitigasi struktural/non-struktural & peringatan dini), tanggap darurat, serta pasca-bencana (rehabilitasi & rekonstruksi).</p>

<h3>5. Keterampilan Ujian Esai Terbuka & Fieldwork Test (iGeo Standard)</h3>
<p>Format ujian OSN Geografi nasional mengadopsi standar International Geography Olympiad (iGeo) yang terdiri dari 3 ronde: <em>Written Response Test (WRT)</em> berupa esai analisis analitis, <em>Multimedia Test (MMT)</em> dengan durasi singkat berbasis visual, serta <em>Fieldwork Exercise</em> observasi lapangan dan pembuatan peta tata guna lahan rekomendasi.</p>

<blockquote>"Melalui kacamata geografi, setiap jengkal permukaan bumi adalah kanvas interaksi dinamis antara kekuatan alam dan peradaban manusia."</blockquote>', 93, 0);
INSERT INTO articles (id, title, slug, category, categories, date, end_date, author, status, cover_image, focus_keyword, meta_title, meta_description, canonical_url, content, seo_score, is_trashed) VALUES ('art-1', 'Panduan Lengkap Persiapan SNBT 2027: Strategi Lolos PTN Impian dengan Sistem IRT', 'panduan-lengkap-persiapan-snbt-2027', 'SNBT & UTBK', '["SNBT \u0026 UTBK","Tips Belajar \u0026 Prestasi"]', '2026-08-20', '', 'Tim Akademik NLS', 'published', '/images/blog/cover-snbt-2027.jpg', 'persiapan snbt 2027', 'Panduan Lengkap Persiapan SNBT 2027 & Strategi Sistem IRT | NLS', 'Pelajari strategi jitu menghadapi SNBT 2027 dengan sistem penilaian IRT, pemetaan subtes TPS, dan jadwal tryout intensif bersama Next Level Study.', 'https://next-level-study.com/blog/snbt-2027', '<h2>Mengapa Persiapan SNBT Harus Dimulai Lebih Awal?</h2>
<p>Seleksi Nasional Berbasis Tes (SNBT) merupakan gerbang utama bagi ratusan ribu pejuang PTN di seluruh Indonesia. Dengan sistem penilaian <em>Item Response Theory (IRT)</em>, bobot setiap butir soal ditentukan oleh tingkat kesulitan relatif dan akurasi jawaban seluruh peserta nasional.</p>

<h3>1. Pahami Komposisi Subtes UTBK SNBT</h3>
<ul>
  <li><strong>Tes Potensi Skolastik (TPS):</strong> Penalaran Umum, Pengetahuan Kuantitatif, Pemahaman Bacaan & Menulis, serta Pengetahuan & Pemahaman Umum.</li>
  <li><strong>Literasi dalam Bahasa Indonesia & Bahasa Inggris:</strong> Membaca kritis teks ilmiah, analitis, dan argumentatif.</li>
  <li><strong>Penalaran Matematika:</strong> Pemodelan matematika dalam konteks kehidupan nyata dan pemecahan masalah.</li>
</ul>

<h3>2. Strategi Latihan Try Out Berkelanjutan</h3>
<p>Latihan try out berkala di platform CBT NLS membiasakan Anda dengan interface resmi ujian, manajemen waktu yang ketat, serta analisis skor IRT secara presisi.</p>

<blockquote>"Konsistensi dalam mengevaluasi kelemahan soal jauh lebih berharga daripada mengerjakan ribuan soal tanpa refleksi konsep."</blockquote>', 92, 0);
INSERT INTO articles (id, title, slug, category, categories, date, end_date, author, status, cover_image, focus_keyword, meta_title, meta_description, canonical_url, content, seo_score, is_trashed) VALUES ('art-3', 'Tips Memilih Jurusan Kuliah Sesuai Minat, Bakat, dan Prospek Karier Masa Depan', 'tips-memilih-jurusan-kuliah-masa-depan', 'Tips Belajar & Prestasi', '["Tips Belajar \u0026 Prestasi","Informasi NLS"]', '2026-08-10', '', 'Kak Bima (Statistika UGM)', 'published', '/images/blog/cover-jurusan-kuliah.jpg', 'tips memilih jurusan kuliah', 'Tips Memilih Jurusan Kuliah Sesuai Minat & Prospek Karier | NLS', 'Panduan komprehensif cara memilih jurusan kuliah yang tepat di PTN favorit sesuai minat, bakat, potensi akademik, dan prospek karier masa depan.', 'https://next-level-study.com/blog/memilih-jurusan', '<h2>Salah Jurusan: Masalah Klasik yang Harus Dihindari</h2>
<p>Riset menunjukkan lebih dari 80% mahasiswa di Indonesia merasa salah memilih program studi. Memilih jurusan kuliah adalah keputusan strategis yang akan membentuk lintasan karier dan pengembangan profesional Anda di masa depan.</p>

<h3>Formula 3A dalam Memilih Jurusan</h3>
<ol>
  <li><strong>Aptitude (Bakat & Kemampuan Akademik):</strong> Ukur performa nilai rapor dan skor try out pada mata pelajaran kunci.</li>
  <li><strong>Affinity (Minat & Gairah Belajar):</strong> Bidang apa yang membuat Anda bersemangat untuk belajar secara mandiri tanpa paksaan?</li>
  <li><strong>Application (Peluang Kerja & Tren Industri):</strong> Analisis kebutuhan industri 5-10 tahun ke depan, seperti Data Science, Artificial Intelligence, Green Energy, dan Bioteknologi.</li>
</ol>', 90, 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-jan-1', 'Kick-Off & Diagnostic Test OSN 9 Bidang Sains', 'OSN', 'SMA', 'SMA / MA / Sederajat', '2026-01-11', '', '08:30 - 11:30 WIB', 'Online (CBT & Zoom)', 'Platform CBT LMS Next Level Study', 'Pendaftaran Dibuka', 'Halo Tim NLS, saya ingin mendaftar Kick-Off & Diagnostic Test OSN (11 Januari 2026).', 'Tes diagnostik awal pemetaan kompetensi calon peserta OSN 9 bidang sains untuk menentukan strategi bimbingan tingkat kota/kabupaten.', '["Pemetaan 9 bidang OSN (Matematika, Fisika, Kimia, Biologi, Informatika, Astronomi, Kebumian, Ekonomi, Geografi)","Laporan analisis kekuatan \u0026 kelemahan materi siswa","Rekomendasi modul belajar bertahap dari mentor medalis"]', 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-jan-2', 'Webinar Strategi & Roadmap Lolos SNBT PTN Top 2026', 'SNBT', 'SMA', 'SMA / MA / SMK & Gap Year', '2026-01-18', '', '19:00 - 21:00 WIB', 'Online (Live Zoom Interactive)', 'Live Zoom Room NLS Indonesia', 'Terbuka Umum', 'Halo Tim NLS, saya ingin info Webinar Strategi SNBT 2026 (18 Januari 2026).', 'Kupas tuntas strategi pemilihan program studi, analisis rasionalisasi nilai rapor vs skor UTBK, dan jadwal tahapan resmi SNPMB.', '["Strategi memilih jurusan \u0026 universitas target","Analisis passing grade riil \u0026 bobot subtes SNBT","Sesi tanya jawab langsung bersama konsultan pendidikan NLS"]', 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-jan-3', 'In-House Training (IHT) Modul Ajar Guru Mitra', 'Mitra Sekolah', 'Guru / Instansi', 'Guru & Tenaga Pendidik', '2026-01-25', '', '08:00 - 15:30 WIB', 'Tatap Muka (Onsite)', 'Aula SMAN 14 Jakarta & Sekolah Mitra', 'Kemitraan Eksklusif', 'Halo Tim NLS, kami tertarik dengan program In-House Training (IHT) Guru Mitra Sekolah.', 'Pelatihan pembuatan perangkat ajar interaktif, asesmen diagnostik, dan integrasi soal HOTS bagi dewan guru sekolah mitra NLS.', '["Penyusunan modul ajar berstandar Kurikulum Merdeka","Bank soal HOTS \u0026 rubrik penilaian berbasis kompetensi","Sertifikat pelatihan 32 JP dari NLS \u0026 Dinas terkait"]', 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-feb-1', 'Try Out Akbar Nasional SNBT 2026 Batch 1 (Sistem IRT)', 'SNBT', 'SMA', 'SMA / MA / SMK & Gap Year', '2026-02-08', '', '08:00 - 12:30 WIB', 'Online (Platform CBT NLS)', 'LMS CBT Next Level Study', 'Pendaftaran Dibuka', 'Halo Tim NLS, saya ingin mendaftar Try Out SNBT Batch 1 (8 Februari 2026).', 'Simulasi ujian UTBK SNBT gelombang 1 dengan algoritma penilaian IRT persis standar BPPP Kemendikbudristek.', '["Simulasi 7 subtes SNBT lengkap dengan timer per sesi","Skor IRT instan keluar disertai analisis peluang prodi","Akses video pembahasan dan modul kunci jawaban"]', 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-feb-2', 'Simulasi Akbar OSN-K 2026 (9 Bidang Sains SMA)', 'OSN', 'SMA', 'SMA / MA / Sederajat', '2026-02-15', '', '09:00 - 12:00 WIB', 'Online (CBT Berstandar Puspresnas)', 'Platform CBT LMS Next Level Study', 'Simulasi Resmi', 'Halo Tim NLS, saya ingin mendaftar Simulasi OSN-K SMA (15 Februari 2026).', 'Simulasi persiapan OSN Tingkat Kabupaten/Kota (OSN-K) dengan format dan tingkat kesulitan soal yang telah disesuaikan silabus BPTI.', '["Mencakup 9 bidang lomba sains SMA","Perangkingan peserta tingkat nasional \u0026 per provinsi","Review pembahasan soal menantang bersama pembina medalis"]', 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-feb-3', 'Workshop Pembinaan Guru Pembimbing OSN Mitra Dinas', 'Event Dinas', 'Guru / Instansi', 'Guru Sains SMP & SMA', '2026-02-22', '', '08:30 - 16:00 WIB', 'Hybrid (Tatap Muka & Zoom)', 'Auditorium Dinas Pendidikan / Gedung Guru', 'Program Diknas', 'Halo Tim NLS, kami ingin info Workshop Guru Pembina OSN Dinas Pendidikan.', 'Peningkatan kapasitas guru pembina olimpiade sains sekolah untuk mengidentifikasi bakat siswa dan membedah teknik penyelesaian soal lanjut.', '["Bedah kurikulum olimpiade sains nasional \u0026 internasional","Teknik mentoring siswa berpotensi medali","Bahan ajar eksklusif \u0026 bank soal kompetisi NLS"]', 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-mar-1', 'Simulasi OSN-K Jenjang SMP (IPA, IPS & Matematika)', 'OSN', 'SMP', 'SMP / MTs / Sederajat', '2026-03-07', '', '09:00 - 11:30 WIB', 'Online (Platform CBT NLS)', 'LMS CBT Next Level Study', 'Pendaftaran Dibuka', 'Halo Tim NLS, saya ingin mendaftar Simulasi OSN-K SMP (7 Maret 2026).', 'Simulasi khusus pejuang medali SMP pada bidang IPA Terpadu, IPS Terpadu, dan Matematika menjelang seleksi kabupaten resmi.', '["Sistem CBT anti-kecurangan dengan integrasi timer","Analisis skor \u0026 ranking komprehensif se-Indonesia","Sesi live review tips lolos ke tingkat provinsi"]', 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-mar-2', 'Try Out Akbar Nasional SNBT 2026 Batch 2 (Sistem IRT)', 'SNBT', 'SMA', 'SMA / MA / SMK & Gap Year', '2026-03-15', '', '08:00 - 12:30 WIB', 'Online (LMS CBT NLS)', 'Platform CBT LMS Next Level Study', 'Pendaftaran Dibuka', 'Halo Tim NLS, saya ingin mendaftar Try Out SNBT Batch 2 (15 Maret 2026).', 'Try Out SNBT putaran kedua dengan update tipe soal penalaran matematika dan literasi terbaru 2026.', '["Perangkingan nasional dengan puluhan ribu peserta","Analisis akurat daya saing masuk prodi impian di PTN","E-Certificate skor SNBT \u0026 pembahasan video lengkap"]', 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-mar-3', 'Masterclass TKA & Diagnostic Penalaran Akademik 2026', 'TKA', 'SMA', 'SMA / MA / Sederajat', '2026-03-21', '', '13:00 - 16:00 WIB', 'Online (Interactive Zoom)', 'Live Zoom Webinar NLS', 'Terbuka Umum', 'Halo Tim NLS, saya ingin mendaftar Masterclass TKA 2026 (21 Maret 2026).', 'Penguasaan materi Tes Kemampuan Akademik (TKA) untuk persiapan seleksi mandiri PTN (SIMAK UI, UTUL UGM, dll) dan kedinasan.', '["Pendalaman soal-soal penalaran analitik \u0026 numerik tinggi","Trik cepat eliminasi opsi jawaban pengecoh","Modul rangkuman rumus ringkas \u0026 konsep fundamental"]', 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-mar-4', 'LDKS & Character Building Pengurus OSIS Mitra Sekolah', 'Mitra Sekolah', 'SMA', 'Pengurus OSIS & MPK SMA', '2026-03-28', '', '07:30 - 17:00 WIB', 'Tatap Muka (Onsite)', 'Auditorium SMAN 19 Jakarta & Kawasan Outbound', 'Mitra Khusus', 'Halo Tim NLS, kami ingin konsultasi pelaksanaan program LDKS sekolah kami.', 'Pelatihan kepemimpinan, public speaking, manajemen organisasi, dan problem solving bagi pengurus OSIS/MPK sekolah mitra.', '["Simulasi manajemen konflik \u0026 kepemimpinan adaptif","Outbound team building \u0026 leadership challenges","Mentoring personal bersama trainer bersertifikasi"]', 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-apr-1', 'Grand Simulasi UTBK-SNBT Final Sprint 2026', 'SNBT', 'SMA', 'SMA / MA / SMK & Gap Year', '2026-04-05', '', '08:00 - 12:30 WIB', 'Online (Platform CBT NLS)', 'Platform CBT LMS Next Level Study', 'Final Sprint', 'Halo Tim NLS, saya ingin mendaftar Final Sprint SNBT 2026 (5 April 2026).', 'Simulasi pemantapan akhir sebelum hari H UTBK SNBT dengan tingkat akurasi prediksi soal mencapai 95%.', '["Simulasi 100% menyerupai kondisi hari H UTBK","Rekomendasi strategi pengerjaan manajemen waktu","Live konsultasi akhir kesiapan psikologis \u0026 mental"]', 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-apr-2', 'Olimpiade Sains & Matematika SD Se-Jabodetabek (NLS Junior Cup)', 'OSN', 'SD', 'SD / MI (Kelas 4-6)', '2026-04-12', '', '08:30 - 12:00 WIB', 'Hybrid (Online CBT & Final Onsite)', 'Kantor NLS Bekasi Timur & Online', 'Kompetisi Terbuka', 'Halo Tim NLS, saya ingin mendaftarkan siswa untuk NLS Junior Cup SD.', 'Ajang kompetisi sains dan matematika usia dini untuk memupuk bibit juara olimpiade sains nasional sejak sekolah dasar.', '["Kategori Matematika \u0026 IPA SD","Piala bergilir, medali emas-perak-perunggu \u0026 piagam","Beasiswa bimbingan belajar NLS bagi para juara"]', 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-apr-3', 'Bimbingan Intensif Persiapan OSN Tingkat Provinsi (OSN-P)', 'OSN', 'SMA', 'Lolos OSN-K 2026', '2026-04-19', '', '13:00 - 16:30 WIB', 'Online (Live Mentoring Camp)', 'Zoom Premium Classroom NLS', 'Intensif Medalis', 'Halo Tim NLS, saya ingin info Bimbingan Intensif OSN-P (19 April 2026).', 'Program akselerasi materi tingkat lanjut bagi peserta yang telah lolos seleksi kabupaten menuju seleksi provinsi.', '["Bedah tuntas soal-soal isian singkat \u0026 uraian kompleks","Mentoring intensif 1-on-1 bersama alumni medalis IEO/IBO/IMO","Simulasi mingguan dengan feedback detail per nomor soal"]', 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-mei-1', 'Try Out Seleksi Mandiri PTN & Ujian Kedinasan (TKA + SKD)', 'TKA', 'SMA', 'SMA / MA / SMK & Gap Year', '2026-05-10', '', '08:30 - 12:30 WIB', 'Online (Platform CBT NLS)', 'LMS CBT Next Level Study', 'Pendaftaran Dibuka', 'Halo Tim NLS, saya ingin daftar Try Out Mandiri PTN & Kedinasan (10 Mei 2026).', 'Simulasi komprehensif untuk jalur mandiri (SIMAK UI, UM UGM, SM ITB) dan Seleksi Kompetensi Dasar (SKD) Sekolah Kedinasan.', '["Simulasi subtes TKA Saintek / Soshum \u0026 SKD Kedinasan","Pembahasan strategi lolos nilai ambang batas (Passing Grade)","Bank latihan soal eksklusif 1.000+ nomor"]', 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-mei-2', 'Seminar Transformasi Digital Asesmen Sekolah Bersama Disdik', 'Event Dinas', 'Guru / Instansi', 'Kepala Sekolah & Operator Kurikulum', '2026-05-24', '', '08:30 - 15:00 WIB', 'Tatap Muka & Live Streaming', 'Hotel Santika / Grand Ballroom Bekasi', 'Disdik Official', 'Halo Tim NLS, kami ingin hadir di Seminar Transformasi Digital Asesmen Dinas.', 'Kerjasama NLS dan Dinas Pendidikan membahas integrasi Computer Based Testing (CBT) mandiri dan analisis data akademik siswa.', '["Implementasi platform ujian digital aman anti-curang","Pengolahan analitik nilai rapor untuk pemetaan mutu sekolah","MOU kemitraan penyediaan Try Out berkala bagi sekolah negeri/swasta"]', 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-jun-1', 'Summer Bootcamp OSN Nasional 2026 (Pelatda Medalis)', 'OSN', 'SMA', 'Peserta OSN Nasional', '2026-06-14', '', '08:00 - 17:00 WIB', 'Hybrid (Camp Tatap Muka & Online)', 'Pusat Pembinaan NLS & Zoom Classroom', 'National Camp', 'Halo Tim NLS, saya ingin mendaftar Summer Bootcamp OSN Nasional 2026.', 'Karantina bimbingan intensif persiapan Olimpiade Sains Nasional tingkat puncak bersama para peraih medali internasional.', '["Pembahasan silabus olimpiade internasional (IBO, IPhO, IChO, IMO, IOI, IEO)","Eksperimen laboratorium virtual \u0026 praktikum analitis","Simulasi ujian 4 jam beruntun standar Puspresnas"]', 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-jun-2', 'Workshop Pembekalan Kurikulum Internasional (Cambridge & IB)', 'TKA', 'SMP', 'SMP & SMA Sekolah Internasional', '2026-06-21', '', '10:00 - 13:00 WIB', 'Online (Interactive Zoom)', 'Live Zoom Classroom NLS', 'Terbuka Umum', 'Halo Tim NLS, saya tertarik dengan program Kurikulum Cambridge & IB.', 'Persiapan materi kurikulum Cambridge (IGCSE, AS & A-Level) dan International Baccalaureate (IB DP) untuk tahun ajaran baru.', '["Pemahaman syllabus breakdown IGCSE \u0026 A-Level","Strategi penulisan essay \u0026 past paper problem solving","Mentoring oleh lulusan universitas top luar negeri"]', 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-jul-1', 'Orientation & Academic Diagnostic Test Tahun Ajaran Baru', 'TKA', 'SMA', 'Siswa Baru Kelas 10, 11, 12 SMA', '2026-07-19', '', '08:30 - 11:30 WIB', 'Online (CBT NLS)', 'Platform CBT LMS Next Level Study', 'Pendaftaran Dibuka', 'Halo Tim NLS, saya ingin ikut Diagnostic Test Tahun Ajaran Baru (19 Juli 2026).', 'Pemetaan potensi akademik awal tahun ajaran baru untuk menentukan kelas bimbingan minat bakat OSN, SNBT, atau Kurikulum Mandiri.', '["Tes pemetaan gaya belajar \u0026 penguasaan sains/soshum dasar","Rekomendasi kelas bimbingan reguler vs intensif privat","Konsultasi gratis hasil rapor dan rencana studi lanjut"]', 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-jul-2', 'Sesi Motivasi & Strategi Belajar Siswa Baru (MPLS Mitra Sekolah)', 'Mitra Sekolah', 'SMA', 'Siswa Baru SMA Mitra', '2026-07-26', '', '09:00 - 12:00 WIB', 'Tatap Muka (Onsite)', 'Auditorium SMAN 2 Jakarta & Sekolah Rekanan', 'Mitra Sekolah', 'Halo Tim NLS, kami ingin mengundang NLS mengisi sesi akademik MPLS sekolah kami.', 'Sesi motivasi belajar, tips lolos PTN sejak kelas 10, dan pengenalan kompetisi sains pada rangkaian MPLS sekolah mitra.', '["Sharing session bersama medalis olimpiade \u0026 mahasiswa berprestasi","Penyusunan target portofolio prestasi sekolah","Free access akun latihan CBT NLS untuk seluruh siswa baru"]', 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-agu-1', 'Try Out Nasional Kemerdekaan SNBT 2027 (Batch Early)', 'SNBT', 'SMA', 'SMA Kelas 12 & Alumni', '2026-08-16', '', '08:00 - 12:00 WIB', 'Online (Platform CBT NLS)', 'LMS CBT Next Level Study', 'Spesial Kemerdekaan', 'Halo Tim NLS, saya ingin mendaftar Try Out Kemerdekaan SNBT (16 Agustus 2026).', 'Simulasi perdana untuk angkatan pejuang PTN 2027 dengan edisi spesial Kemerdekaan Indonesia, berhadiah beasiswa belajar.', '["Simulasi UTBK sistem IRT skala nasional","Beasiswa bimbingan belajar penuh untuk ranking 1-10","Webinar live pembahasan bedah soal esensial"]', 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-agu-2', 'Grand Pelatihan Guru Sains & Matematika SD-SMP Mitra Dinas', 'Event Dinas', 'Guru / Instansi', 'Guru Sains & Matematika SD-SMP', '2026-08-23', '', '08:00 - 16:00 WIB', 'Tatap Muka (Onsite)', 'Pusat Pelatihan Pendidik & Tenaga Kependidikan', 'Program Diknas', 'Halo Tim NLS, kami ingin mendaftar Pelatihan Guru Sains Dinas Pendidikan.', 'Workshop pemodelan sains terapan dan metode pembelajaran interaktif untuk meningkatkan nilai Asesmen Nasional sekolah.', '["Praktik pembuatan alat peraga sains sederhana","Teknik pengajaran logika matematika tanpa hafalan rumus","Penyusunan instrumen evaluasi berstandar nasional"]', 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-agu-3', 'Workshop Penguatan Literasi & Numerasi Berbasis CBT Sekolah', 'Mitra Sekolah', 'SMP', 'Siswa SMP / MTs Mitra', '2026-08-27', '', '13:00 - 15:30 WIB', 'Online (LMS CBT NLS)', 'Platform Digital NLS', 'Mitra Sekolah', 'Halo Tim NLS, kami ingin mendaftar Workshop Literasi & Numerasi 27 Agustus 2026.', 'Penguatan penalaran dasar matematika dan literasi baca-tulis dalam format ujian berbasis komputer modern.', '["Latihan 50 soal literasi kontekstual","Evaluasi realtime kecepatan pengerjaan per butir soal","Sertifikat digital untuk seluruh peserta mitra"]', 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-sep-1', 'Simulasi Try Out OSN Jenjang SMA Tahap Seleksi Lanjutan', 'OSN', 'SMA', 'SMA / MA / Sederajat', '2026-09-13', '', '09:00 - 12:00 WIB', 'Online (LMS CBT NLS)', 'Platform CBT LMS Next Level Study', 'Pendaftaran Dibuka', 'Halo Tim NLS, saya ingin daftar Simulasi OSN SMA Tahap Lanjutan (13 September 2026).', 'Uji kemampuan komprehensif untuk 9 bidang sains SMA dengan tingkat kompleksitas setara kompetisi sains internasional.', '["Soal tipe studi kasus analitis \u0026 problem solving","Feedback penilaian terperinci dari juri olimpiade","Peringkat nasional untuk benchmarking kemampuan"]', 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-sep-2', 'Grand Pemetaan Akademik & Try Out Terpadu Mitra Sekolah Se-Jabar', 'Mitra Sekolah', 'SMA', 'Siswa Kelas 10, 11, 12 Mitra', '2026-09-27', '', '08:00 - 15:00 WIB', 'Hybrid (CBT Sekolah & Online)', 'Sekolah-Sekolah Mitra NLS Jawa Barat', 'Kemitraan Akbar', 'Halo Tim NLS, kami ingin mendaftarkan sekolah kami pada Grand Pemetaan Akademik.', 'Penyelenggaraan pemetaan kemampuan akademik serentak untuk puluhan sekolah mitra dengan platform CBT mandiri NLS.', '["Dashboard analitik performa per kelas dan per sekolah","Rekomendasi materi yang perlu penguatan guru","Apresiasi piala sekolah berprestasi akademik terbaik"]', 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-okt-1', 'Try Out Nasional SNBT 2027 Gelombang Pemantapan', 'SNBT', 'SMA', 'SMA / MA / SMK & Gap Year', '2026-10-11', '', '08:00 - 12:30 WIB', 'Online (Platform CBT NLS)', 'Platform CBT LMS Next Level Study', 'Pendaftaran Dibuka', 'Halo Tim NLS, saya ingin mendaftar Try Out SNBT Gelombang Pemantapan (11 Oktober 2026).', 'Simulasi berkala SNBT untuk mengukur progress kenaikan skor IRT siswa setelah mengikuti bimbingan semester ganjil.', '["Grafik perkembangan skor per subtes secara visual","Prediksi peluang masuk klaster PTN Top 10 Indonesia","Bank pembahasan soal yang dapat diakses selamanya"]', 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-okt-2', 'Workshop Bedah Soal & Trik TKA Penalaran Kognitif', 'TKA', 'SMA', 'SMA / MA / Sederajat', '2026-10-25', '', '13:00 - 15:30 WIB', 'Online (Live Zoom Interactive)', 'Zoom Room NLS Indonesia', 'Terbuka Umum', 'Halo Tim NLS, saya ingin daftar Workshop Bedah Soal TKA Kognitif (25 Oktober 2026).', 'Mengupas tuntas pola soal penalaran induktif, deduktif, serta penalaran spasial yang sering menjadi kendala siswa.', '["Teknik pemecahan teka-teki logika dan silogisme","Latihan berbatas waktu dengan feedback real-time","E-Booklet 500 latihan soal kognitif mandiri"]', 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-nov-1', 'Simulasi Akbar Olimpiade Puspresnas (LDI, FLS2N, OPSI & FIKSI)', 'OSN', 'SMP', 'SMP & SMA Seluruh Indonesia', '2026-11-08', '', '09:00 - 14:00 WIB', 'Online (Platform Digital NLS)', 'Platform CBT LMS Next Level Study', 'Ajang Puspresnas', 'Halo Tim NLS, saya ingin info Simulasi Olimpiade Puspresnas (8 November 2026).', 'Pembekalan dan simulasi kompetisi talenta nasional mencakup Lomba Debat Indonesia, Festival Seni, serta Riset Penelitian Siswa.', '["Simulasi mosi debat, metodologi penelitian OPSI, dan karya FIKSI","Mentoring oleh dewan juri \u0026 peraih penghargaan nasional","Sertifikat keikutsertaan kompetisi terstandar"]', 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-nov-2', 'Workshop Strategi Manajemen Belajar Menghadapi Ujian Akhir Semester (PAS)', 'Mitra Sekolah', 'SMA', 'SMA / MA Kelas 10, 11, 12', '2026-11-22', '', '10:00 - 12:30 WIB', 'Hybrid (Tatap Muka & Zoom)', 'Sekolah Mitra & Online LMS', 'Mitra Sekolah', 'Halo Tim NLS, kami ingin mengundang program workshop PAS di sekolah kami.', 'Tips menguasai materi ujian sekolah, teknik active recall & spaced repetition untuk meraih nilai rapor maksimal.', '["Rangkuman materi esensial PAS semester 1","Simulasi latihan ujian sekolah berbasis CBT","Konsultasi target rapor untuk syarat SNBP"]', 0);
INSERT INTO events (id, title, category, jenjang, jenjang_label, date, end_date, time, mode, location, badge_text, whatsapp_message, description, highlights, is_trashed) VALUES ('evt-des-1', 'National Grand Try Out SNBT & Year-End Academic Evaluation 2026', 'SNBT', 'SMA', 'SMA / MA / SMK & Gap Year', '2026-12-13', '', '08:00 - 12:30 WIB', 'Online (Platform CBT NLS)', 'Platform CBT LMS Next Level Study', 'Grand Year-End', 'Halo Tim NLS, saya ingin mendaftar National Grand Try Out Year-End 2026.', 'Try Out penutup tahun 2026 dengan skala peserta terbesar se-Indonesia untuk mengukur kesiapan final menghadapi SNBT tahun berikutnya.', '["Perangkingan nasional dengan puluhan ribu peserta se-Indonesia","Analisis komprehensif capaian target belajar tahun 2026","Doorprize gadget belajar, beasiswa NLS, dan e-certificate resmi"]', 0);
INSERT INTO teachers (id, name, short_name, photo, education, categories, jenjang, jenjang_label, subject, subjects, kebutuhan_privat, philosophy, highlights, rating, review_count, is_trashed) VALUES ('t-1', 'Raditya Pratama, S.Si.', 'Kak Radit', '/images/pengajar/mentor-1-math.jpg', 'Matematika ITB (Medalis Emas OSN & IMO Participant)', '["OSN","TKA","Kurikulum Internasional"]', '["SMP","SMA"]', 'SMP, SMA & SPK School', 'Matematika Lanjut (OSN, TKA, & IB / Cambridge)', '["Matematika (SMA)","Matematika (SMP)","Matematika (Wajib)","Matematika Tingkat Lanjut","Matematika Saintek","Matematika (Wajib \u0026 Lanjut)","Matematika SMP","Cambridge / IB Mathematics (HL/SL)","Penalaran Matematika"]', 'Bimbingan intensif persiapan OSN Matematika, Ujian Mandiri PTN (SIMAK UI & UTUL UGM), serta persiapan ujian Cambridge AS/A-Level & IB Math HL.', 'Matematika bukan tentang menghafal rumus, melainkan melatih kejujuran logika dan daya nalar terstruktur.', '["Membimbing 20+ siswa peraih medali OSN \u0026 KSN Nasional","Tutor privat intensif Cambridge A-Level Math \u0026 IB DP HL","Alumni bimbingan diterima di STEI ITB, Fasilkom UI, \u0026 NTU Singapura"]', 4.9, 24, 0);
INSERT INTO teachers (id, name, short_name, photo, education, categories, jenjang, jenjang_label, subject, subjects, kebutuhan_privat, philosophy, highlights, rating, review_count, is_trashed) VALUES ('t-2', 'Dr. Nurul Azizah, M.Biotech.', 'Kak Nurul', '/images/pengajar/mentor-2-bio.jpg', 'Bioteknologi UI & Univ. of Melbourne (Peraih IBO Award)', '["OSN","SNBT","Kurikulum Nasional","Kurikulum Internasional","TKA"]', '["SMA"]', 'SMA Kelas 10-12 & Gap Year', 'Biologi Kedokteran, Sains Terapan & Literasi IPA', '["Biologi (SMA)","Biologi","Biologi Saintek","Biologi SMA","Cambridge / IB Biology (IGCSE \u0026 A-Level)","TPS - Kemampuan Penalaran Umum (KPU)","TPS - Pengetahuan \u0026 Pemahaman Umum (PPU)"]', 'Les privat masuk Fakultas Kedokteran (IUP & Reguler UI/UGM), OSN Biologi, dan IB DP Biology HL.', 'Mengajar dengan hati nurani dan kejujuran ilmiah melahirkan calon dokter dan saintis yang berintegritas.', '["Mentor tim olimpiade biologi Puspresnas \u0026 IUP Medicine","Berhasil meloloskan 65+ siswa ke FK UI, FK UGM, \u0026 FK Unair","Spesialis genetika molekuler, fisiologi manusia, dan biokimia"]', 4.9, 24, 0);
INSERT INTO teachers (id, name, short_name, photo, education, categories, jenjang, jenjang_label, subject, subjects, kebutuhan_privat, philosophy, highlights, rating, review_count, is_trashed) VALUES ('t-3', 'Bima Satria Wicaksana, M.Sc.', 'Kak Bima', '/images/pengajar/mentor-3-snbt.jpg', 'Statistika UGM & Data Science UI (Skor UTBK 850+)', '["SNBT","TKA","Kurikulum Nasional"]', '["SMA"]', 'SMA Kelas 11-12 & Alumni', 'SNBT TPS Penalaran Kuantitatif & Logika Matematika', '["TPS - Penalaran Kuantitatif \u0026 Logika Matematika","Penalaran Matematika","Matematika (Wajib)","Matematika Tingkat Lanjut","TPS - Kemampuan Penalaran Umum (KPU)","Matematika Saintek","Matematika Soshum","Matematika (Wajib \u0026 Lanjut)"]', 'Privat intensif tembus PTN klaster 1, penguasaan pola soal penalaran analitis, dan sistem pembobotan IRT SNBT.', 'Kelolosan PTN impian adalah buah kedisiplinan, strategi penalaran terarah, dan latihan yang jujur.', '["Pakar analisis data skor IRT SNBT dan pemetaan peluang jurusan PTN","Telah mendampingi ribuan siswa lolos ITB, UI, UGM, ITS, \u0026 Undip","Metode pembahasan konsep mendalam tanpa rumus sesat"]', 4.9, 24, 0);
INSERT INTO teachers (id, name, short_name, photo, education, categories, jenjang, jenjang_label, subject, subjects, kebutuhan_privat, philosophy, highlights, rating, review_count, is_trashed) VALUES ('t-4', 'Citra Kirana Wardhani, M.Pd.', 'Kak Citra', '/images/pengajar/mentor-4-literasi.jpg', 'Pendidikan Bahasa & Sastra Univ. Indonesia', '["SNBT","Kurikulum Nasional","Kurikulum Internasional","TKA"]', '["SMP","SMA"]', 'SMP, SMA & Gap Year', 'Literasi Bahasa Indonesia, English for Academic & SNBT', '["Bahasa Indonesia (Wajib)","Bahasa Inggris (Wajib)","Bahasa Indonesia Tingkat Lanjut","Bahasa Inggris Tingkat Lanjut","Bahasa Indonesia (SMP)","Bahasa Indonesia (SD)","Literasi dalam Bahasa Indonesia","Literasi dalam Bahasa Inggris","TPS - Pemahaman Bacaan \u0026 Menulis (PBM)","TPS - Pengetahuan \u0026 Pemahaman Umum (PPU)","Bahasa Indonesia SMA","Bahasa Inggris SMA","Bahasa Indonesia SMP","Bahasa Inggris SMP","Academic English / IELTS \u0026 TOEFL"]', 'Privat literasi teks kompleks SNBT, peningkatan nilai rapor Bahasa Kurikulum Merdeka, serta TOEFL/IELTS persiapan IUP.', 'Literasi kritis adalah pondasi integritas berpikir dan komunikasi seorang calon intelektual.', '["Penulis panduan strategi literasi membaca SNBT standar BPPP","Instruktur privat bahasa Inggris akademik dan persiapan IUP PTN","Tingkat kepuasan bimbingan 4.98/5.0 dari ratusan siswa"]', 4.9, 24, 0);
INSERT INTO teachers (id, name, short_name, photo, education, categories, jenjang, jenjang_label, subject, subjects, kebutuhan_privat, philosophy, highlights, rating, review_count, is_trashed) VALUES ('t-5', 'Muhammad Rafi Pratama, S.T.', 'Kak Rafi', '/images/pengajar/mentor-5-physics.jpg', 'Teknik Elektro ITB (Medalis Fisika Nasional)', '["OSN","TKA","SNBT","Kurikulum Internasional"]', '["SMA"]', 'SMA & Alumni', 'Fisika Saintek, OSN Fisika & Cambridge Physics', '["Fisika (SMA)","Fisika","Fisika Saintek","Fisika SMA","Cambridge / IB Physics (IGCSE \u0026 A-Level)","TPS - Penalaran Kuantitatif \u0026 Logika Matematika"]', 'Privat pemahaman konsep dasar fisika sekolah, persiapan OSN Fisika, SIMAK UI Saintek, dan Cambridge IGCSE/A-Level.', 'Memahami fenomena fisika secara runtut dan jujur membuat soal tersulit pun menjadi sangat logis.', '["Instruktur privat SIMAK UI, UTUL UGM, dan seleksi beasiswa luar negeri","Spesialis mekanika kuantum dasar, elektrodinamika, dan termodinamika","Membina siswa medalis OSN-P dan OSN Nasional 2024-2025"]', 4.9, 24, 0);
INSERT INTO teachers (id, name, short_name, photo, education, categories, jenjang, jenjang_label, subject, subjects, kebutuhan_privat, philosophy, highlights, rating, review_count, is_trashed) VALUES ('t-6', 'Drs. Hendra Gunawan, M.Si.', 'Pak Hendra', '/images/pengajar/mentor-6-senior-math.jpg', 'Magister Pendidikan UNJ (Guru Teladan & Praktisi Kurikulum)', '["Kurikulum Nasional","TKA","OSN"]', '["SD","SMP","SMA","Guru / Instansi"]', 'SD, SMP, SMA & Pelatihan Guru', 'Matematika Kurikulum Merdeka, Ujian Sekolah & Asesmen', '["Matematika (SMA)","Matematika (SMP)","Matematika (SD)","Matematika (Wajib)","Matematika Tingkat Lanjut","Pendidikan Pancasila dan Kewarganegaraan","Matematika (Wajib \u0026 Lanjut)","Matematika SMP","Matematika SD","Matematika Saintek","Matematika Soshum"]', 'Pendampingan privat siswa dari tingkat dasar hingga mahir, peningkatan nilai rapor untuk jalur SNBP, dan persiapan ASAJ.', 'Setiap anak berhak memahami matematika dengan sabar dan menyenangkan tanpa rasa takut.', '["Pengalaman lebih dari 20 tahun membimbing siswa sukses tembus sekolah \u0026 PTN unggulan","Penyusun kurikulum pembelajaran adaptif berstandar Kurikulum Nasional","Instruktur pelatihan guru dan narasumber edukasi"]', 4.9, 24, 0);
INSERT INTO teachers (id, name, short_name, photo, education, categories, jenjang, jenjang_label, subject, subjects, kebutuhan_privat, philosophy, highlights, rating, review_count, is_trashed) VALUES ('t-7', 'Stephanie Lauren, B.Sc., M.Ed.', 'Ms. Stephanie', '/images/pengajar/mentor-7-chem-intl.jpg', 'Univ. of Melbourne & Cambridge Certified Teacher', '["Kurikulum Internasional","OSN","TKA"]', '["SMP","SMA"]', 'SMP & SMA Sekolah Internasional / SPK', 'Chemistry & Science (IB DP HL/SL, Cambridge IGCSE / A-Level)', '["Kimia (SMA)","Kimia","Kimia Saintek","Kimia SMA","Bahasa Inggris (Wajib)","Bahasa Inggris Tingkat Lanjut","Cambridge / IB Chemistry (IGCSE \u0026 A-Level)","Academic English / IELTS \u0026 TOEFL"]', 'Privat bilingual siswa SPK / Internasional school (Jakarta Intercultural School, British School, ACS, SIS, Bina Bangsa, dll).', 'Global competence with deep scientific integrity empowers students to lead the world.', '["Tutor spesialis IB Internal Assessment (IA) \u0026 Extended Essay Chemistry","Alumni bimbingan diterima di NUS, Melbourne Univ, NTU, Oxford, \u0026 UI IUP","Pengantar bilingual 100% fluent English atau campuran bahasa Indonesia"]', 4.9, 24, 0);
INSERT INTO teachers (id, name, short_name, photo, education, categories, jenjang, jenjang_label, subject, subjects, kebutuhan_privat, philosophy, highlights, rating, review_count, is_trashed) VALUES ('t-8', 'Rara Anindya, S.E., M.M.', 'Kak Rara', '/images/pengajar/mentor-8-econ.jpg', 'Ilmu Ekonomi FEB UI (Lulusan Tercepat & Cumlaude)', '["TKA","SNBT","Kurikulum Nasional","Kurikulum Internasional","OSN"]', '["SMA"]', 'SMA Kelas 10-12 & Gap Year', 'Ekonomi Soshum, OSN Ekonomi, Akuntansi & Cambridge', '["Ekonomi (SMA)","Ekonomi","Ekonomi Soshum","Ekonomi \u0026 Akuntansi SMA","Cambridge / IB Economics \u0026 Business","TPS - Penalaran Kuantitatif \u0026 Logika Matematika"]', 'Privat persiapan masuk FEB UI, UGM, Unair, dan bimbingan Cambridge AS/A-Level Economics & Business Studies.', 'Ekonomi mengajarkan kejujuran dalam mengelola amanah, efisiensi, dan keadilan sosial.', '["Mentor privat intensif UTBK Soshum \u0026 SIMAK UI KKI (Kelas Khusus Internasional)","Spesialis analisis mikro-makro ekonomi dan akuntansi keuangan","Membimbing ratusan siswa sukses masuk FEB PTN favorit"]', 4.9, 24, 0);
INSERT INTO teachers (id, name, short_name, photo, education, categories, jenjang, jenjang_label, subject, subjects, kebutuhan_privat, philosophy, highlights, rating, review_count, is_trashed) VALUES ('t-9', 'Rocheline Angela, S.Pd.', 'Kak Rocheline', '/images/pengajar/mentor-9-sd-sains.jpg', 'Pendidikan Dasar & Sains Anak Berprestasi', '["Kurikulum Nasional","OSN","TKA"]', '["SD","SMP"]', 'SD (Kelas 1-6) & SMP (Kelas 7-9)', 'Calistung, Matematika & IPA Eksploratif SD/SMP', '["Matematika (SD)","Bahasa Indonesia (SD)","IPA (SD)","IPS (SD)","Matematika (SMP)","Bahasa Indonesia (SMP)","IPA (SMP)","IPS (SMP)","Matematika SD","IPA / IPAS SD","Bahasa Indonesia SD","Bahasa Inggris SD","Calistung \u0026 Tematik SD","Matematika SMP","IPA SMP (Fisika \u0026 Biologi)"]', 'Les privat intensif anak SD/SMP untuk persiapan OSN Cilik, Ujian Sekolah, pembentukan karakter belajar mandiri, dan juara kelas.', 'Menumbuhkan rasa ingin tahu dan kejujuran belajar sejak dini adalah investasi terbaik masa depan anak.', '["Spesialis metode visual gamification \u0026 concrete-pictorial-abstract","Membimbing puluhan siswa SD/SMP meraih ranking 1 dan medali OSN","Sabar, interaktif, dan sangat disukai anak-anak"]', 4.9, 24, 0);
INSERT INTO teachers (id, name, short_name, photo, education, categories, jenjang, jenjang_label, subject, subjects, kebutuhan_privat, philosophy, highlights, rating, review_count, is_trashed) VALUES ('t-10', 'Oslando Wibowo, S.Kom., M.T.', 'Kak Oslando', '/images/pengajar/mentor-10-cs.jpg', 'Ilmu Komputer UI (Coach Tim Olimpiade & Software Architect)', '["OSN","Kurikulum Internasional","TKA"]', '["SMP","SMA"]', 'SMP, SMA & Mahasiswa', 'Informatika OSN, Coding (C++, Python), & AP Computer Science', '["Informatika / Komputer (SMA)","SMK - Projek Kreatif \u0026 Kejuruan","Cambridge / AP Computer Science \u0026 Coding","TPS - Penalaran Kuantitatif \u0026 Logika Matematika"]', 'Privat olimpiade komputer (OSN Informatika), persiapan AP Computer Science SPK school, dan portofolio Beasiswa BIM / IISMA.', 'Coding dan algoritma melatih daya pemecahan masalah yang sistematis, presisi, dan jujur.', '["Coach tim olimpiade sains informatika tingkat nasional dan internasional","Master algoritma Dynamic Programming, Graph, dan Data Structures","Membimbing siswa masuk Fasilkom UI, STEI ITB, \u0026 Computer Science NUS"]', 4.9, 24, 0);
INSERT INTO teachers (id, name, short_name, photo, education, categories, jenjang, jenjang_label, subject, subjects, kebutuhan_privat, philosophy, highlights, rating, review_count, is_trashed) VALUES ('t-11', 'Dimas Arya Pradipta, S.Si.', 'Kak Dimas', '/images/pengajar/mentor-5-physics.jpg', 'Astronomi ITB (Medalis Olimpiade Astronomi Internasional IOAA)', '["OSN","TKA","Kurikulum Nasional"]', '["SMA"]', 'SMA & Alumni', 'OSN Astronomi, Astrofisika & Fisika Lanjut SMA', '["Astronomi (SMA)","Fisika (SMA)","Fisika","Fisika Saintek","Fisika SMA"]', 'Persiapan intensif OSN Astronomi dari tingkat Kabupaten hingga Nasional & Pelatnas IOAA, serta konsep mekanika benda langit.', 'Memahami alam semesta dimulai dari kerendahan hati dan ketelitian sains yang jujur.', '["Medalis Olimpiade Astronomi \u0026 Astrofisika Internasional (IOAA)","Membimbing puluhan finalis dan peraih medali OSN Astronomi","Instruktur pengamatan teleskop dan pengolahan data astronomi digital"]', 4.9, 24, 0);
INSERT INTO teachers (id, name, short_name, photo, education, categories, jenjang, jenjang_label, subject, subjects, kebutuhan_privat, philosophy, highlights, rating, review_count, is_trashed) VALUES ('t-12', 'Farhan Fauzi, S.T.', 'Kak Farhan', '/images/pengajar/mentor-1-math.jpg', 'Teknik Geologi UGM (Peraih Medalis Emas IESO)', '["OSN","TKA","Kurikulum Nasional"]', '["SMA"]', 'SMA & Gap Year', 'OSN Kebumian, Geologi, Meteorologi & Oseanografi', '["Kebumian (SMA)","Geografi (SMA)","Geografi","Geografi Soshum","Geografi SMA"]', 'Pendampingan privat OSN Kebumian, geologi dinamis, meteorologi, hidrologi, dan astronomi dasar untuk seleksi Puspresnas.', 'Ilmu kebumian membina kepekaan terhadap kelestarian bumi dan integritas seorang saintis.', '["Medalis Emas International Earth Science Olympiad (IESO)","Coach olimpiade kebumian di berbagai SMA unggulan nasional","Spesialis kristalografi, mineralogi, dan interpretasi peta geologi"]', 4.9, 24, 0);
INSERT INTO teachers (id, name, short_name, photo, education, categories, jenjang, jenjang_label, subject, subjects, kebutuhan_privat, philosophy, highlights, rating, review_count, is_trashed) VALUES ('t-13', 'Nadia Safitri, S.Pd., M.Sc.', 'Kak Nadia', '/images/pengajar/mentor-4-literasi.jpg', 'Pendidikan Geografi UI & Univ. Gadjah Mada', '["OSN","TKA","Kurikulum Nasional"]', '["SMP","SMA"]', 'SMP, SMA & Gap Year', 'OSN Geografi, IPS Terpadu SMP, & Geografi Soshum', '["Geografi (SMA)","Geografi","Sosiologi","Sosiologi SMA","Sosiologi Soshum","IPS (SMP)","IPS (SD)","Geografi Soshum","Geografi SMA","IPS SMP"]', 'Persiapan OSN Geografi SMA, OSN IPS SMP, Ujian Sekolah Geografi, dan pendalaman materi UTBK Geografi Soshum.', 'Geografi mengajarkan cara pandang holistik, keterikatan ruang hidup, dan cinta tanah air.', '["Pembina tim olimpiade sains geografi dan IPS tingkat nasional","Penulis modul pendalaman spasial SIG dan demografi kependudukan","Tingkat kelulusan siswa bimbingan ke PTN favorit mencapai 94%"]', 4.9, 24, 0);
INSERT INTO teachers (id, name, short_name, photo, education, categories, jenjang, jenjang_label, subject, subjects, kebutuhan_privat, philosophy, highlights, rating, review_count, is_trashed) VALUES ('t-14', 'Alief Kurnia, S.Si.', 'Kak Alief', '/images/pengajar/mentor-3-snbt.jpg', 'Biologi & Ilmu Alam ITB (Pelatih Tim OSN IPA SMP)', '["OSN","Kurikulum Nasional","TKA"]', '["SD","SMP"]', 'SD Kelas 4-6 & SMP Kelas 7-9', 'OSN IPA SMP, Biologi & Fisika Terpadu Eksploratif', '["IPA (SMP)","IPA (SD)","IPA SMP (Fisika \u0026 Biologi)","IPA / IPAS SD","Biologi (SMA)","Biologi"]', 'Persiapan OSN IPA SMP (Fisika & Biologi), OSN IPA SD Cilik, serta pemantapan sains integratif untuk sekolah unggulan.', 'Membangun logika sains yang kokoh sejak bangku SMP adalah kunci keunggulan di jenjang selanjutnya.', '["Coach tim OSN IPA SMP peraih medali emas \u0026 perak nasional","Penyusun praktikum sains virtual dan pembahasan soal problem solving","Pendekatan pembelajaran yang komunikatif, runut, dan menyenangkan"]', 4.9, 24, 0);
INSERT INTO teachers (id, name, short_name, photo, education, categories, jenjang, jenjang_label, subject, subjects, kebutuhan_privat, philosophy, highlights, rating, review_count, is_trashed) VALUES ('t-15', 'Gabriella Maya, S.Sos.', 'Kak Maya', '/images/pengajar/mentor-8-econ.jpg', 'Sosiologi & Ilmu Sosial Universitas Indonesia', '["OSN","TKA","Kurikulum Nasional"]', '["SMP","SMA"]', 'SMP & SMA', 'OSN IPS SMP, Sosiologi Soshum & Sejarah Indonesia', '["IPS (SMP)","IPS (SD)","IPS SMP","Sosiologi","Sosiologi SMA","Sosiologi Soshum","Sejarah","Sejarah Soshum","Antropologi","Pendidikan Pancasila dan Kewarganegaraan"]', 'Persiapan OSN IPS SMP, pemahaman materi Sosiologi & Sejarah untuk Ujian Mandiri PTN / UTBK Soshum.', 'Belajar ilmu sosial melatih empati sosial dan daya analisis fenomena kemanusiaan secara jujur.', '["Medalis olimpiade sains bidang ilmu sosial tingkat nasional","Telah mendampingi ratusan siswa SMP \u0026 SMA tembus sekolah dan PTN impian","Metode mind mapping analitis yang mudah diingat tanpa hafalan buta"]', 4.9, 24, 0);
INSERT INTO teacher_applications (id, submitted_at, status, nama, panggilan, wa, email, pendidikan, photo, categories, jenjang, jenjang_label, subject, kebutuhan_privat, philosophy, highlights, portfolio, notes) VALUES ('app-sample-1', '2026-08-27T10:30:00.000Z', 'pending', 'Fajar Hidayatullah, M.Sc.', 'Kak Fajar', '081234567890', 'fajar.hidayat@gmail.com', 'S2 Fisika Teori Universitas Indonesia (Medalis Perak OSN Fisika)', '/images/pengajar/mentor-2-physics.jpg', '["OSN","Kurikulum Internasional"]', '["SMP","SMA"]', 'SMP & SMA', 'Fisika Kuantum & Mekanika Lanjut (OSN & IPhO)', 'Bimbingan intensif seleksi OSN Fisika tingkat Kabupaten hingga Nasional, serta persiapan IGCSE & A-Level Physics.', 'Memahami fenomena alam melalui logika matematika yang elegan dan eksperimen pemikiran.', '["Medali Perak OSN Fisika Tingkat Nasional","Alumni S2 Fisika Universitas Indonesia (Cumlaude)","Berpengalaman 4+ tahun membimbing 15+ peraih medali OSN-P"]', 'https://drive.google.com/file/d/sample-cv-fajar/view', 'Calon mentor sangat direkomendasikan untuk pembinaan OSN Fisika.');
INSERT INTO teacher_applications (id, submitted_at, status, nama, panggilan, wa, email, pendidikan, photo, categories, jenjang, jenjang_label, subject, kebutuhan_privat, philosophy, highlights, portfolio, notes) VALUES ('app-sample-2', '2026-08-26T15:45:00.000Z', 'pending', 'Nabila Azzahra, S.Si.', 'Kak Nabila', '085712349876', 'nabila.azzahra@ugm.ac.id', 'Kimia Universitas Gadjah Mada (Top 3 LKTI Nasional)', '/images/pengajar/mentor-3-chem.jpg', '["OSN","SNBT"]', '["SMA"]', 'SMA & Alumni', 'Kimia Organik & Stoikiometri UTBK SNBT', 'Pemahaman mendalam reaksi organik, termokimia, dan trik cepat penalaran analitik SNBT.', 'Kimia bukan menghafal rumus, melainkan memahami interaksi partikel dan aplikasi nyata.', '["Juara 1 Lomba Cepat Tepat Kimia Regional Jawa-Bali","Tutor Kimia UTBK SNBT dengan 92% kelolosan siswa ke PTN Top","Penulis modul pemantapan stoikiometri intensif"]', 'https://linkedin.com/in/nabila-azzahra-chem', '');
INSERT INTO programs (id, title, slug, category, jenjang, description, features, link_url, is_active) VALUES ('prog-osn', 'Bimbel Olimpiade Sains Nasional (OSN)', 'bimbel-osn', 'Bimbel OSN', 'SD, SMP, SMA', 'Pembinaan intensif 9 bidang sains bersama mentor medalis nasional dan internasional.', '["Kurikulum Terstruktur", "Mentor Medalis", "Platform CBT Interaktif", "Rapor & Analisis Nilai"]', '/bimbel-osn', 1);
INSERT INTO programs (id, title, slug, category, jenjang, description, features, link_url, is_active) VALUES ('prog-snbt', 'Bimbel Persiapan UTBK-SNBT', 'bimbel-snbt', 'Bimbel SNBT', 'SMA & Alumni', 'Simulasi try out berbasis IRT presisi, drilling penalaran skolastik, dan bedah trik pengerjaan cepat.', '["Kurikulum Terstruktur", "Mentor Medalis", "Platform CBT Interaktif", "Rapor & Analisis Nilai"]', '/bimbel-snbt', 1);
INSERT INTO programs (id, title, slug, category, jenjang, description, features, link_url, is_active) VALUES ('prog-tka', 'Bimbel Tes Kemampuan Akademik (TKA)', 'bimbel-tka', 'Bimbel TKA', 'SMP & SMA', 'Pemantapan materi akademik mendalam untuk ujian sekolah unggulan dan seleksi masuk perguruan tinggi.', '["Kurikulum Terstruktur", "Mentor Medalis", "Platform CBT Interaktif", "Rapor & Analisis Nilai"]', '/bimbel-tka', 1);
INSERT INTO programs (id, title, slug, category, jenjang, description, features, link_url, is_active) VALUES ('prog-nexgen', 'Nexgen Academy (Bimbel Offline Bekasi)', 'nexgen', 'Nexgen Academy', 'SD, SMP, SMA', 'Kelas tatap muka eksklusif dengan fasilitas modern, studio CBT, dan pendampingan mentor juara.', '["Kurikulum Terstruktur", "Mentor Medalis", "Platform CBT Interaktif", "Rapor & Analisis Nilai"]', '/nexgen', 1);
INSERT INTO programs (id, title, slug, category, jenjang, description, features, link_url, is_active) VALUES ('prog-privat', 'Program Les Privat 1-on-1', 'privat', 'Privat', 'SD, SMP, SMA, Internasional', 'Mentoring personal 1 siswa 1 mentor dengan kurikulum fleksibel: Nasional, Cambridge IGCSE, A-Level, & IB Diploma.', '["Kurikulum Terstruktur", "Mentor Medalis", "Platform CBT Interaktif", "Rapor & Analisis Nilai"]', '/privat', 1);
INSERT INTO programs (id, title, slug, category, jenjang, description, features, link_url, is_active) VALUES ('prog-mitra-sekolah', 'Kemitraan Sekolah & In-House Training', 'mitra-sekolah', 'Mitra Sekolah', 'Institusi Sekolah', 'Penyelenggaraan try out akbar sekolah, pelatihan guru, dan karantina persiapan olimpiade.', '["Kurikulum Terstruktur", "Mentor Medalis", "Platform CBT Interaktif", "Rapor & Analisis Nilai"]', '/mitra-sekolah', 1);
INSERT INTO programs (id, title, slug, category, jenjang, description, features, link_url, is_active) VALUES ('prog-mitra-dinas', 'Kemitraan Dinas Pendidikan & B2G', 'mitra-dinas', 'Mitra Dinas', 'Dinas & Lembaga', 'Program pembinaan sains daerah skala besar dan pengadaan resmi institusi terdaftar SIPLaH.', '["Kurikulum Terstruktur", "Mentor Medalis", "Platform CBT Interaktif", "Rapor & Analisis Nilai"]', '/mitra-dinas', 1);
INSERT INTO system_settings (key, value, description) VALUES ('site_name', 'Next Level Study (NLS)', 'Nama Situs Resmi');
INSERT INTO system_settings (key, value, description) VALUES ('site_tagline', 'Era Baru Pendidikan: Ekosistem Bimbingan OSN, SNBT, & Les Privat Terdepan', 'Tagline Brand');
INSERT INTO system_settings (key, value, description) VALUES ('contact_whatsapp', '+62 851-6307-0002', 'Nomor Resmi WhatsApp Hotline');
INSERT INTO system_settings (key, value, description) VALUES ('contact_email', 'nextlevelstudyindonesia@gmail.com', 'Email Resmi NLS');
INSERT INTO system_settings (key, value, description) VALUES ('office_address', 'Jalan Pahlawan No. 26, Duren Jaya, Bekasi Timur, Jawa Barat 17111', 'Alamat Kantor Pusat');
INSERT INTO system_settings (key, value, description) VALUES ('database_version', '1.0.0', 'Versi Skema Relasional SQLite');
INSERT INTO system_settings (key, value, description) VALUES ('last_sync_time', '2026-08-27T20:13:16.3787271+07:00', 'Waktu Sinkronisasi Database Terakhir');
COMMIT;
