$c = [System.IO.File]::ReadAllText("c:\Users\vc\Documents\nls-blog-hame\nls-blog-hame\index.html", [System.Text.Encoding]::UTF8)
Write-Host "1. Has Melihat Lebih Dekat:" $c.Contains("Melihat Lebih Dekat Next Level Study")
Write-Host "2. Has id=kaleidoskop:" $c.Contains('id="kaleidoskop"')
Write-Host "3. Has id=kalender:" $c.Contains('id="kalender"')
Write-Host "4. Has id=berita:" $c.Contains('id="berita"')
Write-Host "5. Position check kaleidoskop < kalender:" ($c.IndexOf('id="kaleidoskop"') -lt $c.IndexOf('id="kalender"'))
Write-Host "6. Position check kalender < berita:" ($c.IndexOf('id="kalender"') -lt $c.IndexOf('id="berita"'))
Write-Host "7. Has homeCalendarApp():" $c.Contains("homeCalendarApp()")
Write-Host "8. Has default-events.js:" $c.Contains("/kalender/default-events.js")
